# Docker containers used for development only.

services:
    redis:
        container_name: penelope-redis
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - ./data/redis:/data
        restart: always

    mongo:
        container_name: penelope-mongo
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - ./data/mongo:/data/db
        env_file:
            - docker.env
        command: --replSet rs0 --bind_ip_all

    mongoclient:
        container_name: penelope-mongoclient
        image: mongo
        depends_on:
            - mongo
        volumes:
            - ./dev_scripts:/dev_scripts
        env_file:
            - docker.env
        entrypoint:
            - /dev_scripts/initiate_replica.sh

version: "3"
